CREATE TABLE IF NOT EXISTS `persons` (
  `id` int(6) NOT NULL auto_increment,
  `name` varchar(128) NOT NULL,
  `nickname` varchar(128) NOT NULL,
  `company` varchar(128) NOT NULL,
  `position` varchar(128) NOT NULL,
  `activity` text NOT NULL,
  `willhelp` text NOT NULL,
  `needhelp` text NOT NULL,
  `other` text NOT NULL,
  `region_id` varchar(200) NOT NULL,
  `forumprofile` varchar(255) NOT NULL,
  `phone` varchar(128) NOT NULL,
  `icq1` varchar(128) NOT NULL,
  `email` varchar(128) NOT NULL,
  `password` varchar(32) NOT NULL,
  `visibility` int(1) NOT NULL,
  `views` int(6) NOT NULL,
  `timestamp` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `icq` varchar(48) NOT NULL,
  `url` varchar(128) NOT NULL,
  `pathToPicture` varchar(32) NOT NULL,
  `govnumber` varchar(10) NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `nickname` (`nickname`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 